# **📌 Introduction aux Tenseurs dans PyTorch 🚀**

Bienvenue dans ce nouveau chapitre ! Aujourd’hui, on va parler des tenseurs, la base de tout en deep learning et en machine learning. Si vous voulez maîtriser PyTorch, vous devez comprendre les tenseurs !

Un tenseur, c’est simplement une structure de données qui permet de représenter des informations sous forme numérique. Par exemple :

Une image peut être représentée comme un tenseur de forme [3, 224, 224], où 3 représente les trois canaux de couleur (Rouge, Vert, Bleu), 224 la hauteur, et 224 la largeur.

Un tableau de données peut être un tenseur de forme [N, M] où N est le nombre de lignes et M le nombre de colonnes.

Un son peut être un tenseur 1D représentant l’amplitude des ondes sonores sur le temps.

Bref, tout ce que vous traitez en machine learning peut être transformé en tenseur ! Maintenant, passons à la pratique.

In [ ]:
import torch

**1️⃣ Le Scalaire (Tenseur 0D)**

Un scalaire, c’est un seul nombre. En PyTorch, c’est un tenseur à 0 dimension :

In [ ]:
S = torch.tensor(7)
S

tensor(7)

In [ ]:
S.ndim

0

In [ ]:
S.item()

7

**2️⃣ Le Vecteur (Tenseur 1D)**

Un vecteur, c’est un ensemble de nombres alignés dans une seule dimension :

In [ ]:
V = torch.tensor([1,2,3])
V

tensor([1, 2, 3])

In [ ]:
V.ndim

1

In [ ]:
V.size()

torch.Size([3])

**3️⃣ La Matrice (Tenseur 2D)**

Une matrice, c’est un tableau à 2 dimensions :

In [ ]:
M = torch.tensor([[1,2],[4,5]])
M

tensor([[1, 2],
        [4, 5]])

In [ ]:
M.ndim

2

In [ ]:
M.shape

torch.Size([2, 2])

**4️⃣ Le Tenseur Général (Tenseur ND)**

Un tenseur peut avoir plus de 2 dimensions ! Voici un exemple 3D :

In [ ]:
T = torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
T.ndim

3

In [ ]:
T.shape

torch.Size([1, 3, 3])

# 📌Exemple détaillé : Comprendre le shape d'un tenseur en PyTorch

Imaginons ce tenseur en notation mathématique :

$$
\text{TENSEUR} =
\begin{bmatrix}
\begin{bmatrix} \begin{bmatrix} 1 & 2 & 3\end{bmatrix} \\\begin{bmatrix} 4 & 5 & 6 \end{bmatrix} \end{bmatrix},
\begin{bmatrix}\begin{bmatrix} 7 & 8 & 9 \end{bmatrix}\\\begin{bmatrix} 10 & 11 & 12 \end{bmatrix}
\end{bmatrix}\end{bmatrix}
$$

### 🔹 Représentation en PyTorch


In [ ]:
TENSEUR = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]])
TENSEUR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
TENSEUR.ndim

3

In [ ]:
TENSEUR.shape

torch.Size([2, 2, 3])

**📌 Comment compter les dimensions d’un tenseur ?**

Il y a une règle simple pour connaître le nombre de dimensions d’un tenseur en PyTorch :

👉 Comptez les crochets [ les plus extérieurs !

Exemple :

In [ ]:
A= torch.tensor(7)
A.ndim
B=torch.tensor([1,2,3])
B.ndim
C=torch.tensor([[[[1,2,3]]]])
C.ndim

4

**📌 Récapitulatif**

| **Nom**      | **Définition**                                 | **Dimensions** | **Notation courante** |
|-------------|----------------------------------------------|--------------|-----------------|
| **Scalaire** | Un seul nombre                              | `0D`         | `a, x`          |
| **Vecteur**  | Une liste de nombres                       | `1D`         | `y, b`          |
| **Matrice**  | Un tableau avec plusieurs lignes et colonnes | `2D`         | `X, W`          |
| **Tenseur**  | Un tableau multi-dimensionnel               | `ND`         | `T, Z`          |


  **🎲 Création de Tenseurs Aléatoires**

 🔥 **Pourquoi les tenseurs aléatoires sont-ils importants ?**  
 📌 En deep learning, les modèles commencent avec des valeurs aléatoires qu'ils ajustent progressivement.

 🏗 **Étapes du machine learning** :
 1. **Démarrer avec des nombres aléatoires** 🔢
 2. **Analyser les données** 📊
 3. **Ajuster les nombres** 🔄
 4. **Répéter jusqu'à l'optimisation !** 🔁

 ➡️ Créons nos premiers tenseurs aléatoires 🚀


In [ ]:
torch.rand(size = (2,3))

tensor([[0.0653, 0.8784, 0.6151],
        [0.2376, 0.4160, 0.2079]])

  **🖼 Tenseur représentant une image**

 💡 On peut générer un tenseur avec une **forme typique d'image** `(224, 224, 3)`, où :
 - `224x224` représente la résolution
 - `3` correspond aux **canaux RGB**

 ➡️ **Testons ça !** 👇



In [ ]:
image = torch.rand(size = (224,224,3))
image

tensor([[[0.5182, 0.4078, 0.2087],
         [0.7476, 0.4059, 0.1959],
         [0.4632, 0.1734, 0.2458],
         ...,
         [0.9586, 0.5138, 0.9193],
         [0.6435, 0.4252, 0.5946],
         [0.3321, 0.0376, 0.4976]],

        [[0.0255, 0.8983, 0.0233],
         [0.5048, 0.5083, 0.3439],
         [0.4331, 0.7608, 0.2660],
         ...,
         [0.8041, 0.4282, 0.8729],
         [0.9778, 0.7543, 0.0796],
         [0.2364, 0.1075, 0.3010]],

        [[0.4197, 0.2808, 0.0345],
         [0.2696, 0.9238, 0.1086],
         [0.0472, 0.6488, 0.4955],
         ...,
         [0.9818, 0.7421, 0.8326],
         [0.3468, 0.6008, 0.8018],
         [0.9471, 0.5732, 0.5329]],

        ...,

        [[0.0444, 0.2796, 0.0401],
         [0.1477, 0.5557, 0.0541],
         [0.5691, 0.9902, 0.9729],
         ...,
         [0.5429, 0.2030, 0.1023],
         [0.7934, 0.3214, 0.9837],
         [0.1522, 0.5450, 0.3961]],

        [[0.5299, 0.7196, 0.9161],
         [0.5236, 0.0707, 0.9978],
         [0.

**🏗 Tenseurs de Zéros et de Uns**

 📌 **Pourquoi utiliser des tenseurs remplis de 0 ou 1 ?**  
 ✅ Utile pour **masquer des valeurs**, créer des **masques binaires**, ou initialiser certains poids.

 ➡️ Créons des **matrices pleines de 0 et de 1** ! 🔥


In [ ]:
torch.zeros(size = (3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones(size = (3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 **📈 Génération de Plages de Nombres**

 🔢 **Besoin de générer une suite de nombres ?**  
 Utilisons **torch.arange()** pour créer des séquences en un clin d'œil ! ⏳


In [ ]:
zero_to_nine = torch.arange(start = 0, end = 10, step = 2)
zero_to_nine

tensor([0, 2, 4, 6, 8])

  **🔥 Opérations sur les Tenseurs**

 📌 **Manipuler les tenseurs = cœur du deep learning !**

 - ➕ Addition
 - ➖ Soustraction
 - ✖️ Multiplication
 - ➗ Division

 ➡️ **Testons ces opérations !** 👇

In [ ]:
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

  **🏋️‍♂️ Multiplication Matricielle (Deep Learning)**

 **🔑 Règles de multiplication matricielle :**

 - **Les dimensions internes doivent correspondre** 🎯  
   - `(3, 2) @ (3, 2)` ❌ (erreur)
   - `(2, 3) @ (3, 2)` ✅ (ok)
   - `(3, 2) @ (2, 3)` ✅ (ok)

 - **Le résultat a la forme des dimensions externes**  
   - `(2, 3) @ (3, 2) → (2, 2)`
   - `(3, 2) @ (2, 3) → (3, 3)`

 ➡️ **Passons à la pratique !** 🚀

In [ ]:
mat1 = torch.rand(size=(2,3))
mat2 = torch.rand(size = (3,4))

Mat_resul = torch.matmul(mat1,mat2)
Mat_resul

tensor([[0.1666, 0.5017, 0.1413, 0.5376],
        [0.6011, 1.0043, 0.1281, 0.2886]])